apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: faqjxjm7d-python-gitops
  description: This is GitOps manifest for faqjxjm7d-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=faqjxjm7d-python
    backstage.io/kubernetes-id: faqjxjm7d-python 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: faqjxjm7d-python
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:faqjxjm7d-python
